config/routes.rb
Rails.application.routes.draw do
  resources :certificates

  # get 'certificates/:id/download' => 'certificates#download', as: :download_certificate
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  max_paginates_per 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: %i[ show edit update destroy ]

  # GET /certificates?page=1 or /certificates.json
  def index
    @certificates = Certificate.page params[:page]
  end

  # GET /certificates/1 or /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates or /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: "Certificate was successfully created." }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1 or /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: "Certificate was successfully updated." }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1 or /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: "Certificate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def certificate_params
      params.require(:certificate).permit(:pem, :subject, :issuer, :expires_at, :certtype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_with(model: certificate) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
        <% certificate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pem %>
    <%= form.text_area :pem %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :issuer %>
    <%= form.text_field :issuer %>
  </div>

  <div class="field">
    <%= form.label :expires_at %>
    <%= form.date_select :expires_at %>
  </div>


  <%= form.select :certtype, [["Root", "0"], ["Intermediate", "1"], ["Leaf", "2"]] %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/certificates/edit.html.erb
<h1>Editing Certificate</h1>

<%= render 'form', certificate: @certificate %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Certificates</h1>

<table>
  <thead>
    <tr>
      <th>Pem</th>
      <th>Subject</th>
      <th>Issuer</th>
      <th>Expires at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%= certificate.pem %></td>
        <td><%= certificate.subject %></td>
        <td><%= certificate.issuer %></td>
        <td><%= certificate.expires_at %></td>
        <td><%= link_to 'Show', certificate %></td>
        <td><%= link_to 'Edit', edit_certificate_path(certificate) %></td>
        <td><%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certificate', new_certificate_path %>

<%= paginate @certificates %>

app/views/certificates/new.html.erb
<h1>New Certificate</h1>

<%= render 'form', certificate: @certificate %>

<%= link_to 'Back', certificates_path %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<% if @certificate.pem.blank? %>
  CErt is empty!
<% end %>

<p>
  <strong>Pem:</strong>
  <%= @certificate.pem %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @certificate.subject %>
</p>

<p>
  <strong>Issuer:</strong>
  <%= @certificate.issuer %>
</p>

<p>
  <strong>Expires at:</strong>
  <%= @certificate.expires_at %>
</p>

<%= link_to 'Edit', edit_certificate_path(@certificate) %> |
<%= link_to 'Back', certificates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Certtool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>